# Generated by Django 3.2.3 on 2021-07-01 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20210701_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file_info',
            old_name='date',
            new_name='create_at',
        ),
    ]
