# Generated by Django 3.2.3 on 2021-05-18 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_checklog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserStatus',
        ),
    ]
